const Strings = {
    AppName: "Wellness",
    Ok: "Ok",
    Cancel: "Cancel",
    AskMeLater: "Ask me later",
    Login: "LOGIN",
    RememberMe: "Remember Me",
    ForgotPassword: "Forgot Password?",
    LogOut: "Log out?",
    DontHaveAccount: "Don't have an account?",
    OpenCamera: "Open Camera",
    OpenGallery: "Open Gallery",
    SignUp: "Sign Up",
    MyDashboard: "My Dashboard",
    MyActivity: "My Activity",
    Wellness: "Wellness",
    Activities: "Activities",
    Submit: "Submit",
    Save: "Save",
    Welcome: "Welcome",
    LoginToContinue: "Login to continue",
    LetsCreateAccount: "Let's create your account",
    email: 'Email Address',
    forgotYourPassword: 'Forgot Your Password?',
    enterYourEmail: 'Enter your email address to retrieve your password',
    submit: 'SUBMIT',
    forgotPassword: 'Forgot Password',
    oldPassword: 'Old Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    ChangePassword: 'Change Password',
    Confirm: 'Confirm',
    SelectADate: 'Select a date',
    SelectDob: 'Select DOB',
    Male: "Male",
    Female: "Female",
    Other: "Other",
    SelectGender: "Select Gender",
    FullName: "Full Name",
    EmailAddress: "Email address",
    ContactNumber: "Contact Number",
    Password: "Password",
    MyActivity: "My Activity",
    Rewards: "Rewards",
    Profile: "Profile",
    Dashboard: "Dashboard",
    TryAgain: "Try Again",

    Filter: "Filter",
    AllActivity: "All",
    SelectDuration: "Select Duration",
    SelectAction: "Select Action",
    NoDuration: "No duration",
    PerDayDuration: "Per day duration",
    TotalDuration: "Total duration",
    NotSelected: "Not selected",
    Daily: "Daily",
    Weekly: "Weekly",

    Details: 'Details',
    duration: 'Duration (Total)',
    timeSpend: 'Time Spend(Daily)',
    creditPoint: 'Credit Points',
    description: 'Description',
    planThisActivity: 'PLAN THIS ACTIVITY',
    minutes:' Minutes',
    days:' Days',
    day:' Day',

    PlanThisActivity : "PLAN THIS ACTIVITY",
    SelectDate : "Select Date",
    SelectTime : "Select Time",
    Schedule : "Schedule",
    Availability : "Availability",
    SelectAvailability : "Select Availability",
    
    Planned : "Planned",
    InProgress : "In Progress",
    Completed : "Completed",
    
    Finish : "Finish",
    DoYouWantPauseActivity : "Do you want to pause the activity ?",


    EmailRequired: "Email Required !!",
    PasswordRequired: 'Password required !!',
    FullNameRequired: 'Full name required !!',
    GenderRequired: 'Gender Required !!',
    WrongEmail: "Wrong Email !!",
    WeakPassword: 'Weak Password !!',

    //Warnings
    CantConnectRightNow: "Can't connect right now.",
    CheckYourConnection: "Please check your connection or try again later.",
    CameraNotAvailable: "Camera not available on the device.",
    PermissionRequired: "Permission Required",
    AllowCameraGalleryPermission: "Please allow app to access camera/gallery in settings.",
    OopsSomethingWentWrong: "Oops something went wrong",
    PleaseTryAgainLaterWithPermission: "Please try again later with permission check in settings of device",
    CanceledAction: "You canceled action",
    SomeErrorOccured: "Some error has occured",
    NoDataFound: "No data found",
    NoActivityFound: "No activities found",
    NoActivityDetailFound: "No activity detail found",
    SessionTimeOutTitle: "Session Timeout",
    SessionTimeOutMsg: "Your session is timed out. Please try login again.",
    PerformActivityForAtLeastOneMinBeforeFinish: "Please perform activity for at least more than one minute before finishing it.",
    FinishedActivityForTodayAlready: "Sorry, You have finished this activity for today already. You will be able to perform activity next day.",

    //Validaton
    IncorrectEmailValidation: 'Please enter valid email address',
    EmailEmptyValidation: 'Please enter your email address',
    FullNameEmptyValidation: 'Please enter your full name',
    GenderSelectValidation: 'Please select your gender',
    PasswordEmptyValidation: 'Please enter your password',
    SelectTimeAbove30MinValidation: 'Please select time 30 mins above current time.',
    SelectTimeAbove15MinValidation: 'Please select time 15 mins above current time.',
    SelectPerDayDurationValidation: "Please select per day duration for activity.",
    SelectAvailabilityValidation: "Please select availability for activity.",
    IncorrectPasswordalidation: 'Password should be minimum 8 characters long and contain 1 digit,1 Capital letter,1 small letter and special char like !*@#$%^&+=',






}

export default Strings